### ISSUE TITLE
Update If/elseif with switch case statems

### ISSUE THREAD

**Issue by vgpastor** [anmabe06/dirlister#1]
Hi

I recomend you use swithc case statements to improve perfomance and upgrade the capabilities to expand your code.

https://linuxize.com/post/bash-case-statement/

https://github.com/anmabe06/dirlister/blob/48167a591b83d1b26b5b5e407b7f88681e52aa22/.dirlister.sh#L34-L51

Regards!

**Comment by anmabe06** [comment]
Issue adressed!
[#7a8884cc87c90f2f2e22c3b22fd25a3b7382f0fb](https://github.com/anmabe06/dirlister/commit/7a8884cc87c90f2f2e22c3b22fd25a3b7382f0fb)

Thanks for your help!!
